name: Test

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
   
    clt-help:
        name: CLT misc tests
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Prepare manticore-load Docker image
            run: |
              cd test
              ./build.sh
          - name: Run CLT tests
            uses: manticoresoftware/clt@0.2.3
            with:
              image: manticore-load
              test_prefix: test/clt-tests/misc/
              run_args: --privileged

    clt-insert:
        name: CLT basic tests
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Prepare manticore-load Docker image
            run: |
              cd test
              ./build.sh
          - name: Run CLT tests
            uses: manticoresoftware/clt@0.2.3
            with:
              image: manticore-load
              test_prefix: test/clt-tests/basic/
              run_args: --privileged
